### ISSUE TITLE
Wrong namespace

### ISSUE THREAD

**Issue by eldermoraes** [nagypeter/weblogic-kubernetes-operator-on-OKE#2]
Hi,

On this tutorial:

https://github.com/nagypeter/weblogic-kubernetes-operator-on-OKE/blob/master/tutorials/setup.weblogic.kubernetes.md

When running the script:

`./create-weblogic-domain.sh -i create-weblogic-domain-inputs.yaml -o <PATH>`

It raises this error:

```
Checking to see if the secret domain1-weblogic-credentials exists in namespace default
Error from server (NotFound): secrets "domain1-weblogic-credentials" not found
[ERROR] The secret domain1-weblogic-credentials was not found in namespace default
[ERROR] The errors listed above must be resolved before the script can continue
```

It was supposed to do this check on namespace "domain1", right? 

What could be wrong?

**Comment by MaciejGruszka** [comment]
What did you place as targetNamespace when you created operator? I mean what is the value of this field in the create-weblogic-operator-inputs.yaml

To get running WLS the easiest is to follow tutorial at https://github.com/nagypeter/HOL6283/blob/master/tutorials/setup.weblogic.kubernetes.md <https://github.com/nagypeter/HOL6283/blob/master/tutorials/setup.weblogic.kubernetes.md> 
It shows what should be the values of the yaml file to get domain running

Maciej

**Comment by eldermoraes** [comment]
Yes, I did. Has just cleaned up everything and run again and everything worked!

Thanks anyway.
